server:
  port: 8000

spring:
    freemarker:
      check-template-location: false
    profiles:
      active: dev
    jackson:
      time-zone: GMT+8
    data:
      redis:
        repositories:
          enabled: false

    #配置 Jpa
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      open-in-view: true

    redis:
      #数据库索引
      database: 0
      host: 120.79.187.66
      port: 6379
      password: thingsmatrix@8
      #连接超时时间

# 微信小程序配置
wxMini:
  appId: wxb3467842ead8b165
  secret: 5510af4163da6541a2cd961dbbe71f03
